[project]
name = "backend"
version = "0.1.0"
description = "N/A"
readme = "index.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "joblib>=1.5.2",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
    "tensorflow>=2.20.0",
]
